In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values     #از ستون 3 تا یکی مانده به آخری
y = dataset.iloc[:, -1].values       #ستون آخر

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])       #تبدیل جنسیت به داده عددی ترتیبی

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing  import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))          #تبدیل شهر ها به داده های باینری

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
#استاندارسازی داده ها برای ایجاد داده بهینه برای شبکه های عصبی
from  sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
#Initializing the ANN
ann = tf.keras.models.Sequential()

In [13]:
#Add Input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [14]:
#Add second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
#Add Output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [16]:
#Compiling the ANN
# optimizer=adam ---> SGD
# loss---> because output is binary
# metrics  ----> معیار ارزیابی= دقت
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# training ann on training set
# batch_size ---> تعداد داده هایی که در هر مرحله درون مدل قرار میگیرد
# epochs ----> تعداد دفعاتی که مدل باید در هر مرحله همه داده های آموزشی را مرور کند
ann.fit(X_train, y_train, batch_size=32, epochs=100)

In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
[[0.03517566]]


In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

#  [[TN  FP] [FN  TP]]

[[1524   71]
 [ 203  202]]


0.863

In [1]:
!git init

Reinitialized existing Git repository in C:/Users/j-tech.ir/Favorites/.git/


In [9]:
!git commit -m "ANN Tutorial"

[main 99da101] ANN Tutorial
 1 file changed, 677 insertions(+)
 create mode 100644 ANN.ipynb
